### ISSUE TITLE
Number of Packages in Excel Upload

### ISSUE THREAD

**Issue by osammanee** [NAFITH/IraqWeb#1]
Number of Packages in Excel Upload doesn't match actual number of container inside the created BoL
![penguins](https://cloud.githubusercontent.com/assets/14270604/11168411/95d0d182-8b96-11e5-895c-4b3e7af34f66.jpg)
[New Text Document.txt](https://github.com/NAFITH/IraqWeb/files/34850/New.Text.Document.txt)

This is an amendment by Asma

**Comment by hhirzallah** [comment]
fixed

**Comment by aalhadi** [comment]
This is the QA team Comment

**Comment by aalhadi** [comment]
Please Check the image below , I'm still getting the same error after trying to add a BOL from the excel sheet , this sheet contain a values in the number of packages column does not match the actual number of the Containers that listed in the same sheet for the same BOL.  

![bug](https://cloud.githubusercontent.com/assets/15855657/11206569/9dbcf0d2-8d18-11e5-883b-2b99f61ce36b.png)

Here is a copy of the excel data that I was trying to import .
![bug](https://cloud.githubusercontent.com/assets/15855657/11206629/08689d32-8d19-11e5-812c-724eb2e4cfc7.png)

**Comment by aalhadi** [comment]
Please Note the following  :  
1. The successful BOLs are not in the database.
2. The Status of the manifest  status changed to Planned ( although there is no a single BOL connected to this  manifest( Manifest  in the previous comment  )  ) .

**Comment by hhirzallah** [comment]
Fixed
