### ISSUE TITLE
User cannot delete a container from a BOL even If its OPEN ( BOL OR/AND  Container )

### ISSUE THREAD

**Issue by aalhadi** [NAFITH/IraqWeb#718]
§ Role 
•  Nafith Operator 
•  Shipping agent 
§ Prerequisite: 
•  A BOL (Containers)
•  A Container : OPEN 
•  
§ Scenario 
• Login to the system 
• From the main menu, go to BOL then click to view the BOL 
•  view the BOL 
• Enable Edit mode 

§ Bug description 
User cannot delete a container from a BOL even If its OPEN ( BOL OR/AND  Container )

![image](https://cloud.githubusercontent.com/assets/15855657/15008823/8c214460-11eb-11e6-9948-b62d89c1021b.png)

**Comment by hhirzallah** [comment]
Fixed

**Comment by aalhadi** [comment]
Kindly notify us on what are the procedures to check this fix, because currently, this bug is still active, and it is not fixed.

**Comment by hhirzallah** [comment]
Fixed
